# Generated by Django 2.1.2 on 2018-10-27 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='courses.Course'),
            preserve_default=False,
        ),
    ]
