# Generated by Django 2.1.2 on 2018-10-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_speaker_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(default='media/none/no-img.jpg', upload_to='media/'),
        ),
    ]
