# Generated by Django 2.1.2 on 2018-10-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_registration_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseAttribute',
        ),
        migrations.DeleteModel(
            name='SpeakerAttribute',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='media/none/no-img.jpg', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speaker',
            name='degree',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
