# Generated by Django 2.1.2 on 2018-10-27 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20181027_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='speaker',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.Speaker'),
            preserve_default=False,
        ),
    ]
